version: "3.9"

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      start_period: 10s

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - IS_DEBUG
      - SECRET_KEY
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_SERVER
      - MAIL_PORT
      - ALLOWED_HOSTS
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
